
#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

#define CHARACTER_PER_LINE 5
#define NUMBER_OF_PLAYERS 2
#define PLAYER_A 0
#define PLAYER_B 1

#define ACTION_TYPE_ATTACK 1
#define ACTION_TYPE_SKILL 2

#define HEAL_POINT 5
#define HEAL_COOL_DOWN_TURN 4

#define TANK_TARGET_RATE 100
#define TANK_COOL_DOWN_TURN 6

#define DAMAGE_COOL_DOWN_TURN 10

#endif //PROJECT_CONFIG_H
